title: Niki Agrawal, Data Scientist 
logo: /assets/images/bio_circle.png
description: Welcome to my data science portfolio! During my 4-year data science journey in consulting, technology product analytics and engineering research, I have cultivated a passion for delving into complex problems and crafting strategic and technical solutions that bring real value to businesses. I'm skilled in analyzing data and I thrive on fostering collaborative relationships across diverse teams. Please feel free to say hello at nikita24agrawal@gmail.com!
theme: jekyll-theme-minimal
   
